import{S as d,i as u}from"./assets/vendor-BrddEoy-.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))n(t);new MutationObserver(t=>{for(const r of t)if(r.type==="childList")for(const o of r.addedNodes)o.tagName==="LINK"&&o.rel==="modulepreload"&&n(o)}).observe(document,{childList:!0,subtree:!0});function a(t){const r={};return t.integrity&&(r.integrity=t.integrity),t.referrerPolicy&&(r.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?r.credentials="include":t.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function n(t){if(t.ep)return;t.ep=!0;const r=a(t);fetch(t.href,r)}})();const m="32552782-0d4c86680018457e820f20492",h="https://pixabay.com/api/",y=e=>{const s=`${h}?key=${m}&q=${e}&image_type=photo&orientation=horizontal&safesearch=true`;return fetch(s).then(a=>{if(!a.ok)throw new Error(a.status);return a.json()})},g=e=>`<li class="gallery-card">
    <a href="${e.largeImageURL}">
      <img src="${e.webformatURL}" alt="${e.tags}" class="gallery-img" />
    </a>
    <div class="gallery-info">
      <p><span class="label">Likes</span> <span class="value">${e.likes}</span></p>
      <p><span class="label">Views</span> <span class="value">${e.views}</span></p>
      <p><span class="label">Comments</span> <span class="value">${e.comments}</span></p>
      <p><span class="label">Downloads</span> <span class="value">${e.downloads}</span></p>
    </div>
  </li>`,f=e=>{const s=document.querySelector(".js-gallery");s.innerHTML=e.map(g).join(""),b.refresh()},L=e=>{u.warning({title:"Warning",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"})},l=e=>{u.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"})},b=new d(".gallery-card a",{captions:!0,captionsData:"alt",captionPosition:"bottom",captionDelay:250}),p=document.querySelector(".js-search-form"),i=document.querySelector(".js-gallery"),c=document.querySelector(".loader"),v=e=>{e.preventDefault();const s=p.elements.text.value.trim();if(!s){L();return}c.classList.remove("hidden"),y(s).then(a=>{if(a.hits.length===0){l(),i.innerHTML="";return}i.innerHTML="",f(a.hits)}).catch(a=>{l()}).finally(()=>{c.classList.add("hidden")})};p.addEventListener("submit",v);
//# sourceMappingURL=index.js.map
